#!/usr/bin/env bash
# Script that configures a load balancer for Ubuntu 20.04

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\

frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 22370-web-01 100.26.180.218:80 check
	server 22370-web-02 3.230.154.79:80 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
